W5D1/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:new, :create, :show]
  resource :session, only:[:new, :create, :destroy]
  resources :bands, only:[:index, :create, :new, :edit, :show, :update, :destroy]
  
end

W5D1/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence:true
  


end

W5D1/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, presence:true, uniqueness:true
  validates :password_digest, presence:true
  validates :password, length:{minimum:6, allow_nil:true}
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    server_password = BCrypt::Password.new(self.password_digest)
    server_password.is_password?(password)
  end

  def self.find_by_credentials(email, password)
    @user = User.find_by(email: email)
    return nil if @user.nil?
    @user.is_password?(password) ? @user : nil
  end



end

W5D1/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login_user!(user)
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  # def require_logged_in
  #   redirect_to new_session_url unless logged_in?
  # end
  #
  # def require_logged_out
  #   redirect_to user_url
  # end

end

W5D1/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.errors[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find_by(id: params[:id])
    if @band.nil?
      redirect_to bands_url
    else
      render :show
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    redirect_to bands_url
  end

private

  def band_params
    params.require(:band).permit(:name)
  end

end

W5D1/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if @user.nil?
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    else
      login_user!(@user)
      redirect_to user_url(@user)
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

W5D1/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end


private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

W5D1/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W5D1/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D1/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/music_app/app/views/bands/edit.html.erb
<h1>Band Edit</h1>

<% if flash[:errors] %>
  <ul> <% flash[:errors].each do |error| %>
    <li> <%= error %> </li>
  <% end %>
  </ul>
<% end %>

<form action=" <%= band_url(@band) %> " method="post">
<input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="band_name">Band Name:</label>
  <input type="text" id="band_name" name="band[name]" value="<%= @band.name %>">

  <input type="submit" value="SUBMIT">
</form>

W5D1/music_app/app/views/bands/index.html.erb
<h1>All the Bands!</h1>

<% @bands.each do |band| %>
<ul>
  <li> <%= band.name %></li>
</ul>
<% end %>

<form action="<%= new_band_url %>" method="get">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="submit" value="ADD A BAND">
</form>

W5D1/music_app/app/views/bands/new.html.erb
<h1>Band Sign Up</h1>

<% if flash[:errors] %>
  <ul> <% flash[:errors].each do |error| %>
    <li> <%= error %> </li>
  <% end %>
  </ul>
<% end %>

<form action=" <%= bands_url %> " method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="band_name">Band Name:</label>
  <input type="text" id="user_name" name="band[name]">

  <input type="submit" value="SUBMIT">
</form>

W5D1/music_app/app/views/bands/show.html.erb
<p>Current Band: <%= @band.name %></p>

<form action="<%= band_url(@band) %>" method="post">
<input type="hidden" name="_method" value="delete">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="submit" value="DELETE BAND">
</form>

<form action="<%= edit_band_url %>" method="get">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="submit" value="EDIT BAND NAME">
</form>

W5D1/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <header>
    <form action="<%= bands_url %>" method="get">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="HOME">
    </form>

  </header>

  <body>
    <%= yield %>



    <% if logged_in? %>
      <br>

      <p>Current User: <%= current_user.email %></p>

      <p>Not <%= current_user.email %>?</p>
      <form action="<%= session_url %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="submit" value="LOG OUT">
      </form>
    <% end %>

  </body>
</html>

W5D1/music_app/app/views/users/new.html.erb
<h1>User Sign Up</h1>

<% if flash[:errors] %>
  <ul> <% flash[:errors].each do |error| %>
    <li> <%= error %> </li>
  <% end %>
  </ul>
<% end %>

<form action=" <%= users_url %> " method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="user_email">Email:</label>
  <input type="text" id="user_email" name="user[email]">

  <label for="user_password">Password:</label>
  <input type="text" id="user_password" name="user[password]">

  <input type="submit" value="SUBMIT">
</form>

W5D1/music_app/app/views/users/show.html.erb
<h1>Welcome</h1>

  <p>Hi <%= @user.email %></p>